apiVersion: v1
kind: Service
metadata:
  name: #{docker.repo_front}#
  namespace: #{namespace}#
  annotations:
    repo-tag: #{tag}#
  labels:
    deploy: "#{deploy.front}#"
spec:
  selector:
    app: #{docker.repo_front}#
  ports:
  - port: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{docker.repo_front}#
  namespace: #{namespace}#
  annotations:
    repo-tag: #{tag}#
  labels:
    deploy: "#{deploy.front}#"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{docker.repo_front}#
  template:
    metadata:
      annotations:
        repo-tag: #{tag}#
      labels:
        app: #{docker.repo_front}#
    spec:
      containers:
      - name: #{docker.repo_front}#
        image: docker.io/#{docker.username}#/#{docker.repo_front}#:#{tag}#
        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        imagePullPolicy: Always
      imagePullSecrets:
        - name: pullsecret