apiVersion: v1
kind: Service
metadata:
  name: #{docker.repo2}#
  namespace: #{namespace}#
spec:
  selector:
    app: #{app.name}#
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{docker.repo2}#
  namespace: #{namespace}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{app.name}#
  template:
    metadata:
      labels:
        app: #{app.name}#
    spec:
      containers:
      - name: #{docker.repo2}#
        image: docker.io/#{docker.username}#/#{docker.repo2}#:#{tag}#
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "750m"
        env:
        - name: NODE_ENV
          value: #{environment}#
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
        - name: pullsecret