apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: micros
spec:
  selector:
    app: example-app
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: service1
        image: ghcr.io/vriesmarcel/ordering:#{Build.version}#
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "750m"
        env:
        - name: NODE_ENV
          value: prod
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
        - name: pullsecret