apiVersion: v1
kind: Service
metadata:
  name: #{docker.repo1}#
  namespace: #{namespace}#
spec:
  selector:
    app: #{docker.repo1}#
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{docker.repo1}#
  namespace: #{namespace}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{docker.repo1}#
  template:
    metadata:
      labels:
        app: #{docker.repo1}#
    spec:
      containers:
      - name: #{docker.repo1}#
        image: docker.io/#{docker.username}#/#{docker.repo1}#:#{tag}#
        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        env:
        - name: NODE_ENV
          value: #{environment}#
        - name: PORT
          value: "80"
        imagePullPolicy: Always
      imagePullSecrets:
        - name: pullsecret