name: Push front container
permissions:
  actions: write
  packages: write
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string
      frontPath:
        required: true
        type: string
      dockerfileName:
        required: true
        type: string      
      basePath:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_REGISTRY:
        required: true

jobs:
  push_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          sparse-checkout: |
            ${{ inputs.frontPath }}
      
      - name: Copy environment file
        working-directory: ${{github.workspace}}/${{inputs.frontPath}}
        run: |
          cat << EOF > .env
          REACT_APP_BASE_SERVICE1=${{ inputs.basePath }}
          REACT_APP_BASE_SERVICE2=${{ inputs.basePath }}
          EOF 

      - name: Login to Docker
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build image
        working-directory: ${{github.workspace}}/${{inputs.frontPath}}
        run: |
          docker build -t \
          ${{secrets.DOCKER_REGISTRY}}/\
          ${{inputs.frontPath}}:\
          ${{inputs.tag}} \
          --file ${{inputs.dockerfileName}} \
          .

      - name: Scan image Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{secrets.DOCKER_REGISTRY}}/${{inputs.frontPath}}:${{inputs.tag}}
          format: sarif
          output: trivy_results_${{ inputs.frontPath }}_${{ inputs.tag }}.sarif
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy_results_${{ inputs.frontPath }}_${{ inputs.tag }}
          path: trivy_results_${{ inputs.frontPath }}_${{ inputs.tag }}.sarif
          retention-days: 4

      - name: Push image
        run: docker push ${{secrets.DOCKER_REGISTRY}}/${{ inputs.frontPath }}:${{inputs.tag}}