name: Generate sbom
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      microservicePath:
        required: true
        type: string
jobs:
  create_sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            ${{ inputs.microservicePath }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate sbom
        working-directory: ${{ github.workspace }}/${{ inputs.microservicePath }}
        run: |
          npm install
          npx @cyclonedx/cyclonedx-npm --output-file \
          sbom_${{ inputs.microservicePath }}_${{ inputs.tag }}.json
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom_${{ inputs.microservicePath }}_${{ inputs.tag }}
          path: ${{ github.workspace }}/${{ inputs.microservicePath }}/sbom_${{ inputs.microservicePath }}_${{ inputs.tag }}.json
          retention-days: 4