name: On feature branch commit
on:
  push:
    branches: [feature/**]
    paths:
      - "service1/**"
      - "service2/**"
  workflow_dispatch:

env:
  services: "['service1', 'service2']"
  parallel: 2

jobs:
  parameters:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.capture.outputs.services }}
      parallel: ${{ steps.capture.outputs.parallel }}
    steps:
      - name: save workflow parameters
        id: capture
        run: |
          echo "services=${{ env.services }}" >> $GITHUB_OUTPUT
          echo "parallel=${{ env.parallel }}" >> $GITHUB_OUTPUT

  compile_micros:
    runs-on: ubuntu-latest
    needs: parameters
    strategy:
      matrix:
        micro: ${{ fromJson(needs.parameters.outputs.services) }}
      max-parallel: ${{ fromJson(needs.parameters.outputs.parallel) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: compile front
        working-directory: ./react-client
        run: |
          npm install
          npm run build
      - name: compile service
        working-directory: ${{ github.workspace }}/${{ matrix.micro }}
        run: |
          npm install
          node -e 'require("./src/index.js")'