name: On feature branch commit
on:
  push:
    branches: [feature/**]
    paths:
      - "service1/**"
      - "service2/**"
      - "react-client/**"
  workflow_dispatch:
env:
  services: '["service1", "service2"]'
  parallel: 2
jobs:
  build_micros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        micro: ${{ fromJson(env.SERVICES) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: compile front
        working-directory: ./react-client
        run: |
          npm install
          npm run build
      - name: compile service
        working-directory: ${{ github.workspace }}/${{ matrix.micro }}
        run: |
          npm install
          node -e 'require("./src/index.js")'