name: On PR opened
permissions:
  actions: write
  packages: write
  contents: read

on:
  pull_request:
  workflow_dispatch:

env:
  services: '["service1", "service2"]'
  parallel: 2

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yaml
    strategy:
      matrix:
        micro: ${{ fromJson(env.SERVICES) }}
      max-parallel: ${{ env.parallel }}
    with:
      microservicePath: ${{ matrix.micro }}