name: On PR opened
permissions:
  actions: write
  packages: write
  contents: read

on:
  pull_request:
  workflow_dispatch:

jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yaml
    strategy:
      matrix:
        micro:
          - service1
          - service2
      max-parallel: 1
    with:
      microservicePath: ${{ matrix.micro }}