name: On release created
permissions:
  actions: write
  packages: write
  contents: read

on:
  release: 
     types: [published] 
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: micros
    steps:
      - name: get release artifacts for deployment, picks data from latest release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.tag_name }}
          regex: true
          file: ".*"
          target: ${{ github.workspace }}/${{ cluster }}

      - name: set kubernetes context
        uses: azure/k8s-set-context@v3
        id: setcontext
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}} 
 
      - name: provide pull secrets so we can pull the image from gitHub
        uses: azure/k8s-create-secret@v4
        with:
            namespace: '${{env.namespace}}'
            secret-name: 'pullsecret'
            container-registry-url: ${{ secrets.DOCKER_REGISTRY }}
            container-registry-username: ${{ secrets.DOCKER_USERNAME }}
            container-registry-password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: '${{env.namespace}}'
          manifests: |
            ${{ github.workspace }}/${{ cluster }}