name: On release created
permissions:
  actions: write
  packages: write
  contents: read

on:
  release: 
     types: [published]
  workflow_dispatch:

env:
  namespace: micros

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: get release artifacts for deployment, picks data from latest release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          regex: true
          file: ".*\\.yaml"
          target: "cluster/"

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: set kubernetes context
        uses: azure/k8s-set-context@v3
        id: setcontext
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}} 
 
      - name: Create namespace
        run: |
          kubectl create ns ${{ env.namespace }} || echo "El namespace ya existe"

      - name: provide pull secrets so we can pull the image from gitHub
        uses: azure/k8s-create-secret@v4
        with:
            namespace: '${{env.namespace}}'
            secret-name: 'pullsecret'
            container-registry-url: ${{ secrets.DOCKER_REGISTRY }}
            container-registry-username: ${{ secrets.DOCKER_USERNAME }}
            container-registry-password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Helm
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ${{ env.namespace }} --create-namespace

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v5
        with:
          namespace: '${{env.namespace}}'
          manifests: |
            ${{ github.workspace }}/cluster