name: "push container"
permissions:
  actions: write
  packages: write
  contents: read
  security-events: write

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      microservicePath:
        required: true
        type: string
      dockerfileName:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      DOCKER_REGISTRY:
        required: true
      DOCKER_REPO:
        required: true
jobs:
  push_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: gitversion 
        uses: gittools/actions/gitversion/execute@v3.1.11

      - name: Login to Docker
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        working-directory: ${{github.workspace}}/${{inputs.microservicePath}}
        run: |
          docker build -t \
          ${{secrets.DOCKER_REGISTRY}}/\
          ${{secrets.DOCKER_REPO}}:${{env.GitVersion_SemVer}} \
          --file ${{inputs.dockerfileName}} \
          .

      - name: Scan image Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_REPO}}:${{env.GitVersion_SemVer}}
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-results
          path: trivy-results.sarif
          retention-days: 4

      - name: Push image
        run: docker push ${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_REPO}}:${{env.GitVersion_SemVer}}