name: "push container"
permissions:
  actions: write
  packages: write
  contents: read

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      microservicePath:
        required: true
        type: string
      dockerfileName:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        description: github environment
      microservicePath:
        required: true
        type: string
        description: path for microservice
      dockerfileName:
        required: true
        type: string
        description: name for dockerfile to build

jobs:
  push_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '6.0.x'

      - name: Determine Version
        id: gitversion 
        uses: gittools/actions/gitversion/execute@v3.1.11

      - name: Login to Docker
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: select docker driver
        run: |
          docker buildx create --use --driver=docker-container
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
            context: ${{inputs.microservicePath}}
            file: ${{inputs.microservicePath}}/${{inputs.dockerfileName}}
            push: true
            tags: ${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_REPO}}:${{env.GitVersion_SemVer}}
            cache-from: type=gha
            cache-to: type=gha,mode=max