name: "push container"
permissions:
  actions: write
  packages: write
  contents: read
on:
  workflow_call:
    inputs:
      imageRepository:
        required: true
        type: string
      containerRegistry:
        required: true
        type: string
      dockerfilePath:
        required: true
        type: string
    secrets:
      registryPassword:
        required: true
  workflow_dispatch:
    inputs:
      imageRepository:
        required: true
        type: string
        description: image name
      containerRegistry:
        required: true
        type: string
        description: registry name
      dockerfilePath:
        required: true
        type: string
        description: dockerfile location
jobs:
  push_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install GitVersion 
        uses: gittools/actions/gitversion/setup@v0.10.2
        with: 
          versionSpec: '5.x'

      - name: Determine Version 
        id: gitversion 
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Login to GitHUb
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: select docker driver
        run: |
          docker buildx create --use --driver=docker-container
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
            context: ${{github.workspace}}
            file: ${{inputs.dockerfilePath}}
            push: true
            tags: ${{inputs.containerRegistry}}/${{inputs.imageRepository}}:${{env.GitVersion_SemVer}}
            cache-from: type=gha
            cache-to: type=gha,mode=max