name: push container service 1
permissions:
  actions: write
  packages: write
  contents: read

on:
  push:
    branches: ["main"]
    paths:
    - 'service1/**'
  workflow_dispatch:

jobs:
  push_service1:
    uses: ./.github/workflows/push_container.yaml
    with:
      environment: prod
      microservicePath: ${{ github.workspace }}/service1
      dockerfileName: Dockerfile
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_REPO: ${{ secrets.DOCKER_REPO }}