name: Test service
on:
  workflow_call:
    inputs:
      microservicePath:
        required: true
        type: string
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            ${{ inputs.microservicePath }}
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: compile service
        working-directory: ${{ github.workspace }}/${{ inputs.microservicePath }}
        run: |
          npm install
          npm test
      - name: Add report to summary
        working-directory: ${{ github.workspace }}/${{ inputs.microservicePath }}
        run: |
          cat test_results_${{ inputs.microservicePath }}.md >> \
          $GITHUB_STEP_SUMMARY