name: generate sbom
on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate sbom
        working-directory: ./service1
        run: |
          npm install
          npx @cyclonedx/cyclonedx-npm --output-file sbom.json
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: sbom
          path: ./service1/sbom.json
          retention-days: 4